window.MockData = {};

window.MockData.sourceStats = {
  totalAssets: 12,
  buildableAssets: 10,
  builtAssets: 4,
  failedAssets: 1,
  staleAssets: 0,
};

window.MockData.dashboardStats = {
  sources: 18,
  assets: 4432,
  buildableAssets: 4051,
  builtAssets: 2638,
  staleAssets: 119,
};

window.MockData.sourceTypeStats = [
  { label: "文件系统", value: 72, total: 100, tone: "blue" },
  { label: "数据库", value: 17, total: 100, tone: "violet" },
  { label: "网页", value: 11, total: 100, tone: "green" },
];

window.MockData.dataSources = [
  {
    id: "source-local-upload-sales",
    name: "销售资料上传区",
    category: "文件系统",
    connector: "本地上传",
    owner: "王敏",
    status: "可用",
    statusTone: "green",
    maintenanceScope: "全部资产",
    maintenanceTone: "green",
    assets: 12,
    buildable: 10,
    built: 4,
    stale: 0,
    lastInventory: "2026-05-27 14:33",
    changeState: "无源端变更",
    href: "local-upload-detail.html",
  },
  {
    name: "合同归档 Bucket",
    category: "文件系统",
    connector: "S3 / MinIO",
    owner: "法务团队",
    status: "待处理变更",
    statusTone: "amber",
    maintenanceScope: "全部资产",
    maintenanceTone: "green",
    assets: 620,
    buildable: 596,
    built: 412,
    stale: 27,
    lastInventory: "2026-05-26 22:10",
    changeState: "检测到 31 项变化",
    href: "#",
  },
  {
    name: "交付资料 SFTP",
    category: "文件系统",
    connector: "SFTP",
    owner: "交付中心",
    status: "可用",
    statusTone: "green",
    maintenanceScope: "部分资产",
    maintenanceTone: "blue",
    assets: 318,
    buildable: 304,
    built: 211,
    stale: 4,
    lastInventory: "2026-05-27 09:20",
    changeState: "待用户确认",
    href: "#",
  },
  {
    name: "CRM 业务库",
    category: "数据库",
    connector: "PostgreSQL",
    owner: "销售运营",
    status: "可用",
    statusTone: "green",
    maintenanceScope: "未构建",
    maintenanceTone: "amber",
    assets: 148,
    buildable: 138,
    built: 76,
    stale: 6,
    lastInventory: "2026-05-25 18:05",
    changeState: "Schema 无变化",
    href: "#",
  },
  {
    name: "产品帮助中心",
    category: "网页",
    connector: "Sitemap",
    owner: "产品团队",
    status: "盘点中",
    statusTone: "blue",
    maintenanceScope: "部分资产",
    maintenanceTone: "blue",
    assets: 748,
    buildable: 584,
    built: 225,
    stale: 0,
    lastInventory: "2026-05-27 15:02",
    changeState: "正在刷新",
    href: "#",
  },
  {
    name: "研发规范文档",
    category: "文件系统",
    connector: "本地上传",
    owner: "研发效能",
    status: "可用",
    statusTone: "green",
    maintenanceScope: "部分资产",
    maintenanceTone: "blue",
    assets: 132,
    buildable: 126,
    built: 88,
    stale: 3,
    lastInventory: "2026-05-27 10:30",
    changeState: "无源端变更",
    href: "#",
  },
  {
    name: "财务报表归档",
    category: "文件系统",
    connector: "S3 / MinIO",
    owner: "财务中心",
    status: "可用",
    statusTone: "green",
    maintenanceScope: "未构建",
    maintenanceTone: "amber",
    assets: 96,
    buildable: 88,
    built: 41,
    stale: 0,
    lastInventory: "2026-05-26 21:40",
    changeState: "无变化",
    href: "#",
  },
  {
    name: "采购合同 SFTP",
    category: "文件系统",
    connector: "SFTP",
    owner: "采购部",
    status: "待处理变更",
    statusTone: "amber",
    maintenanceScope: "全部资产",
    maintenanceTone: "green",
    assets: 284,
    buildable: 270,
    built: 190,
    stale: 12,
    lastInventory: "2026-05-25 19:22",
    changeState: "检测到 14 项变化",
    href: "#",
  },
  {
    name: "客服工单库",
    category: "数据库",
    connector: "PostgreSQL",
    owner: "客服中心",
    status: "可用",
    statusTone: "green",
    maintenanceScope: "部分资产",
    maintenanceTone: "blue",
    assets: 420,
    buildable: 380,
    built: 306,
    stale: 18,
    lastInventory: "2026-05-27 08:15",
    changeState: "待用户确认",
    href: "#",
  },
  {
    name: "HR 制度 SFTP",
    category: "文件系统",
    connector: "SFTP",
    owner: "人力资源",
    status: "可用",
    statusTone: "green",
    maintenanceScope: "全部资产",
    maintenanceTone: "green",
    assets: 76,
    buildable: 70,
    built: 45,
    stale: 1,
    lastInventory: "2026-05-26 18:09",
    changeState: "无源端变更",
    href: "#",
  },
  {
    name: "方案交付 Bucket",
    category: "文件系统",
    connector: "S3 / MinIO",
    owner: "解决方案",
    status: "待处理变更",
    statusTone: "amber",
    maintenanceScope: "全部资产",
    maintenanceTone: "green",
    assets: 512,
    buildable: 498,
    built: 431,
    stale: 9,
    lastInventory: "2026-05-27 06:45",
    changeState: "检测到 9 项变化",
    href: "#",
  },
  {
    name: "产品设计资料 Bucket",
    category: "文件系统",
    connector: "S3 / MinIO",
    owner: "产品团队",
    status: "可用",
    statusTone: "green",
    maintenanceScope: "部分资产",
    maintenanceTone: "blue",
    assets: 238,
    buildable: 212,
    built: 120,
    stale: 7,
    lastInventory: "2026-05-27 11:12",
    changeState: "检测到 7 项变化",
    href: "#",
  },
  {
    name: "官网页面",
    category: "网页",
    connector: "公开网站",
    owner: "市场部",
    status: "可用",
    statusTone: "green",
    maintenanceScope: "部分资产",
    maintenanceTone: "blue",
    assets: 136,
    buildable: 128,
    built: 84,
    stale: 2,
    lastInventory: "2026-05-26 23:30",
    changeState: "内容 hash 有变化",
    href: "#",
  },
  {
    name: "数据治理手册",
    category: "文件系统",
    connector: "本地上传",
    owner: "数据平台",
    status: "可用",
    statusTone: "green",
    maintenanceScope: "未构建",
    maintenanceTone: "amber",
    assets: 54,
    buildable: 50,
    built: 38,
    stale: 0,
    lastInventory: "2026-05-25 16:45",
    changeState: "无源端变更",
    href: "#",
  },
  {
    name: "销售订单库",
    category: "数据库",
    connector: "MySQL",
    owner: "销售运营",
    status: "连接异常",
    statusTone: "red",
    maintenanceScope: "部分资产",
    maintenanceTone: "blue",
    assets: 89,
    buildable: 82,
    built: 25,
    stale: 11,
    lastInventory: "2026-05-24 09:10",
    changeState: "凭据需要更新",
    href: "#",
  },
  {
    name: "知识库附件 SFTP",
    category: "文件系统",
    connector: "SFTP",
    owner: "知识运营",
    status: "可用",
    statusTone: "green",
    maintenanceScope: "部分资产",
    maintenanceTone: "blue",
    assets: 167,
    buildable: 155,
    built: 91,
    stale: 5,
    lastInventory: "2026-05-27 12:01",
    changeState: "mtime 疑似变化",
    href: "#",
  },
  {
    name: "市场活动资料",
    category: "文件系统",
    connector: "本地上传",
    owner: "市场部",
    status: "可用",
    statusTone: "green",
    maintenanceScope: "全部资产",
    maintenanceTone: "green",
    assets: 72,
    buildable: 68,
    built: 44,
    stale: 0,
    lastInventory: "2026-05-27 13:36",
    changeState: "无源端变更",
    href: "#",
  },
  {
    name: "供应商资料 Bucket",
    category: "文件系统",
    connector: "S3 / MinIO",
    owner: "供应链",
    status: "待处理变更",
    statusTone: "amber",
    maintenanceScope: "全部资产",
    maintenanceTone: "green",
    assets: 310,
    buildable: 292,
    built: 207,
    stale: 14,
    lastInventory: "2026-05-26 20:18",
    changeState: "检测到 18 项变化",
    href: "#",
  },
];

window.MockData.dataSources = window.MockData.dataSources.map((source, index) => {
  const id = source.id || `source-${String(index + 1).padStart(3, "0")}`;
  return {
    ...source,
    id,
    href: `local-upload-detail.html?sourceId=${encodeURIComponent(id)}`,
  };
});

window.MockData.assets = [
  {
    id: "asset-001",
    name: "产品介绍.pdf",
    type: "PDF",
    size: "8.4 MB",
    uploadedAt: "2026-05-27 14:20",
    uploadedBy: "王敏",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "已是最新",
    buildTone: "green",
    lastBuiltAt: "2026-05-27 14:48",
    chunks: 32,
    vectors: 32,
    hash: "sha256: 8af2...91c0",
  },
  {
    id: "asset-002",
    name: "销售话术.docx",
    type: "Word",
    size: "1.7 MB",
    uploadedAt: "2026-05-27 14:21",
    uploadedBy: "王敏",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "未构建",
    buildTone: "amber",
    lastBuiltAt: "-",
    chunks: 0,
    vectors: 0,
    hash: "sha256: 6e19...f3a2",
  },
  {
    id: "asset-003",
    name: "报价模板.xlsx",
    type: "Excel",
    size: "640 KB",
    uploadedAt: "2026-05-27 14:22",
    uploadedBy: "陈浩",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "构建失败",
    buildTone: "red",
    lastBuiltAt: "2026-05-27 15:03",
    chunks: 0,
    vectors: 0,
    hash: "sha256: 44de...7b90",
  },
  {
    id: "asset-004",
    name: "客户案例合集.pptx",
    type: "PPT",
    size: "22.1 MB",
    uploadedAt: "2026-05-27 14:28",
    uploadedBy: "李然",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "已是最新",
    buildTone: "green",
    lastBuiltAt: "2026-05-27 15:12",
    chunks: 74,
    vectors: 74,
    hash: "sha256: c8a0...2db1",
  },
  {
    id: "asset-005",
    name: "扫描合同.png",
    type: "Image",
    size: "3.8 MB",
    uploadedAt: "2026-05-27 14:31",
    uploadedBy: "陈浩",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "已变更",
    buildTone: "blue",
    lastBuiltAt: "2026-05-26 17:10",
    chunks: 0,
    vectors: 0,
    hash: "sha256: 2359...b5d4",
  },
  {
    id: "asset-006",
    name: "加密协议.pdf",
    type: "PDF",
    size: "2.6 MB",
    uploadedAt: "2026-05-27 14:33",
    uploadedBy: "王敏",
    buildability: "加密文件",
    buildabilityTone: "red",
    buildStatus: "不可构建",
    buildTone: "red",
    lastBuiltAt: "-",
    chunks: 0,
    vectors: 0,
    hash: "sha256: 1f70...dad2",
  },
  {
    id: "asset-007",
    name: "渠道政策.md",
    type: "Markdown",
    size: "82 KB",
    uploadedAt: "2026-05-27 14:36",
    uploadedBy: "王敏",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "未构建",
    buildTone: "amber",
    lastBuiltAt: "-",
    chunks: 0,
    vectors: 0,
    hash: "sha256: 9a31...0c82",
  },
  {
    id: "asset-008",
    name: "竞品对比.txt",
    type: "TXT",
    size: "46 KB",
    uploadedAt: "2026-05-27 14:37",
    uploadedBy: "李然",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "未构建",
    buildTone: "amber",
    lastBuiltAt: "-",
    chunks: 0,
    vectors: 0,
    hash: "sha256: 4fb0...a21f",
  },
  {
    id: "asset-009",
    name: "续费流程.pdf",
    type: "PDF",
    size: "5.9 MB",
    uploadedAt: "2026-05-27 14:39",
    uploadedBy: "陈浩",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "已是最新",
    buildTone: "green",
    lastBuiltAt: "2026-05-27 15:18",
    chunks: 28,
    vectors: 28,
    hash: "sha256: b71d...33e4",
  },
  {
    id: "asset-010",
    name: "售前问答.xlsx",
    type: "Excel",
    size: "720 KB",
    uploadedAt: "2026-05-27 14:40",
    uploadedBy: "王敏",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "已变更",
    buildTone: "blue",
    lastBuiltAt: "2026-05-26 16:22",
    chunks: 18,
    vectors: 18,
    hash: "sha256: 7e18...c4a9",
  },
  {
    id: "asset-011",
    name: "区域报价说明.docx",
    type: "Word",
    size: "2.4 MB",
    uploadedAt: "2026-05-27 14:41",
    uploadedBy: "李然",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "构建失败",
    buildTone: "red",
    lastBuiltAt: "2026-05-27 15:24",
    chunks: 0,
    vectors: 0,
    hash: "sha256: e622...51bc",
  },
  {
    id: "asset-012",
    name: "客户分层策略.pptx",
    type: "PPT",
    size: "18.6 MB",
    uploadedAt: "2026-05-27 14:43",
    uploadedBy: "陈浩",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "未构建",
    buildTone: "amber",
    lastBuiltAt: "-",
    chunks: 0,
    vectors: 0,
    hash: "sha256: 0d7c...981a",
  },
];

const assetPathMap = {
  "asset-001": "产品资料/产品介绍.pdf",
  "asset-002": "销售资料/话术/销售话术.docx",
  "asset-003": "销售资料/模板/报价模板.xlsx",
  "asset-004": "客户案例/客户案例合集.pptx",
  "asset-005": "合同扫描/扫描合同.png",
  "asset-006": "合同扫描/加密协议.pdf",
  "asset-007": "销售资料/政策/渠道政策.md",
  "asset-008": "销售资料/竞品/竞品对比.txt",
  "asset-009": "流程制度/续费流程.pdf",
  "asset-010": "销售资料/问答/售前问答.xlsx",
  "asset-011": "销售资料/报价/区域报价说明.docx",
  "asset-012": "客户分层/客户分层策略.pptx",
};

window.MockData.assets = window.MockData.assets.map((asset) => {
  const relativePath = assetPathMap[asset.id] || asset.name;
  const parts = relativePath.split("/");
  return {
    ...asset,
    directory: parts.length > 1 ? parts.slice(0, -1).join("/") : "根目录",
    identity: relativePath,
    relativePath,
  };
});

window.MockData.databaseAssets = [
  {
    id: "db-asset-crm-customer",
    sourceId: "source-004",
    name: "crm_customer",
    displayName: "客户主数据",
    type: "表",
    database: "crm_prod",
    schema: "public",
    comment: "客户主数据，记录客户基础信息、归属销售和生命周期状态。",
    fieldCount: 42,
    primaryKey: "customer_id",
    relationCount: 6,
    rowCount: "1,248,930 行",
    size: "2.4 GB",
    changeStatus: "无变更",
    changeTone: "green",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "已是最新",
    buildTone: "green",
    lastInventoryAt: "2026-05-25 18:05",
    lastBuiltAt: "2026-05-25 18:42",
    chunks: 86,
    vectors: 86,
  },
  {
    id: "db-asset-crm-opportunity",
    sourceId: "source-004",
    name: "crm_opportunity",
    displayName: "销售机会",
    type: "表",
    database: "crm_prod",
    schema: "public",
    comment: "销售机会主表，记录商机阶段、金额、预计签约时间和负责人。",
    fieldCount: 58,
    primaryKey: "opportunity_id",
    relationCount: 8,
    rowCount: "386,214 行",
    size: "1.1 GB",
    changeStatus: "字段变更",
    changeTone: "blue",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "待重建",
    buildTone: "blue",
    lastInventoryAt: "2026-05-25 18:05",
    lastBuiltAt: "2026-05-24 21:16",
    chunks: 64,
    vectors: 64,
  },
  {
    id: "db-asset-crm-contact",
    sourceId: "source-004",
    name: "crm_contact",
    displayName: "客户联系人",
    type: "表",
    database: "crm_prod",
    schema: "public",
    comment: "客户联系人信息，包含联系渠道、职务、是否关键决策人等字段。",
    fieldCount: 36,
    primaryKey: "contact_id",
    relationCount: 4,
    rowCount: "2,906,118 行",
    size: "3.6 GB",
    changeStatus: "无变更",
    changeTone: "green",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "已构建",
    buildTone: "green",
    lastInventoryAt: "2026-05-25 18:04",
    lastBuiltAt: "2026-05-25 18:37",
    chunks: 54,
    vectors: 54,
  },
  {
    id: "db-asset-sales-order-view",
    sourceId: "source-004",
    name: "vw_sales_order_summary",
    displayName: "订单汇总视图",
    type: "视图",
    database: "crm_prod",
    schema: "mart",
    comment: "订单汇总视图，按客户、产品线、区域聚合订单收入和回款状态。",
    fieldCount: 24,
    primaryKey: "",
    relationCount: 5,
    rowCount: "按查询生成",
    size: "视图",
    changeStatus: "无变更",
    changeTone: "green",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "未构建",
    buildTone: "amber",
    lastInventoryAt: "2026-05-25 18:02",
    lastBuiltAt: "-",
    chunks: 0,
    vectors: 0,
  },
  {
    id: "db-asset-contract",
    sourceId: "source-004",
    name: "crm_contract",
    displayName: "合同台账",
    type: "表",
    database: "crm_prod",
    schema: "public",
    comment: "合同台账，记录合同编号、签约主体、金额、有效期和审批状态。",
    fieldCount: 63,
    primaryKey: "contract_id",
    relationCount: 7,
    rowCount: "812,640 行",
    size: "1.9 GB",
    changeStatus: "新增字段",
    changeTone: "blue",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "待重建",
    buildTone: "blue",
    lastInventoryAt: "2026-05-25 18:01",
    lastBuiltAt: "2026-05-23 20:18",
    chunks: 72,
    vectors: 72,
  },
  {
    id: "db-asset-product",
    sourceId: "source-004",
    name: "dim_product",
    displayName: "产品维表",
    type: "表",
    database: "crm_prod",
    schema: "mart",
    comment: "产品维表，描述产品线、型号、版本、生命周期和归属事业部。",
    fieldCount: 31,
    primaryKey: "product_id",
    relationCount: 3,
    rowCount: "18,742 行",
    size: "148 MB",
    changeStatus: "无变更",
    changeTone: "green",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "已构建",
    buildTone: "green",
    lastInventoryAt: "2026-05-25 17:58",
    lastBuiltAt: "2026-05-25 18:30",
    chunks: 38,
    vectors: 38,
  },
  {
    id: "db-asset-region",
    sourceId: "source-004",
    name: "dim_sales_region",
    displayName: "销售区域维表",
    type: "表",
    database: "crm_prod",
    schema: "mart",
    comment: "销售区域维表，维护国家、省区、城市、销售大区和组织归属。",
    fieldCount: 27,
    primaryKey: "region_id",
    relationCount: 2,
    rowCount: "4,126 行",
    size: "42 MB",
    changeStatus: "无变更",
    changeTone: "green",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "未构建",
    buildTone: "amber",
    lastInventoryAt: "2026-05-25 17:57",
    lastBuiltAt: "-",
    chunks: 0,
    vectors: 0,
  },
  {
    id: "db-asset-customer-tag",
    sourceId: "source-004",
    name: "crm_customer_tag",
    displayName: "客户标签关系",
    type: "表",
    database: "crm_prod",
    schema: "public",
    comment: "客户标签关系表，用于描述行业、规模、价值等级和风险标签。",
    fieldCount: 18,
    primaryKey: "customer_id, tag_id",
    relationCount: 4,
    rowCount: "5,812,433 行",
    size: "2.8 GB",
    changeStatus: "无变更",
    changeTone: "green",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "已构建",
    buildTone: "green",
    lastInventoryAt: "2026-05-25 17:56",
    lastBuiltAt: "2026-05-25 18:28",
    chunks: 31,
    vectors: 31,
  },
  {
    id: "db-asset-sales-funnel-view",
    sourceId: "source-004",
    name: "mv_sales_funnel_daily",
    displayName: "每日销售漏斗快照",
    type: "物化视图",
    database: "crm_prod",
    schema: "mart",
    comment: "每日销售漏斗快照，沉淀阶段转化、金额分布和预测达成率。",
    fieldCount: 29,
    primaryKey: "",
    relationCount: 6,
    rowCount: "92,180 行",
    size: "620 MB",
    changeStatus: "无变更",
    changeTone: "green",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "已是最新",
    buildTone: "green",
    lastInventoryAt: "2026-05-25 17:54",
    lastBuiltAt: "2026-05-25 18:44",
    chunks: 44,
    vectors: 44,
  },
  {
    id: "db-asset-activity",
    sourceId: "source-004",
    name: "crm_activity_log",
    displayName: "销售活动日志",
    type: "表",
    database: "crm_prod",
    schema: "public",
    comment: "销售活动日志，包含拜访、电话、邮件、会议等触达记录。",
    fieldCount: 47,
    primaryKey: "activity_id",
    relationCount: 5,
    rowCount: "18,209,771 行",
    size: "12.7 GB",
    changeStatus: "表较大",
    changeTone: "amber",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "构建失败",
    buildTone: "red",
    lastInventoryAt: "2026-05-25 17:50",
    lastBuiltAt: "2026-05-25 19:03",
    chunks: 0,
    vectors: 0,
  },
  {
    id: "db-asset-ticket-case",
    sourceId: "source-009",
    name: "cs_ticket",
    displayName: "客服工单",
    type: "表",
    database: "service_prod",
    schema: "public",
    comment: "客服工单主表，记录问题分类、优先级、处理状态和 SLA 信息。",
    fieldCount: 52,
    primaryKey: "ticket_id",
    relationCount: 7,
    rowCount: "6,204,882 行",
    size: "8.3 GB",
    changeStatus: "无变更",
    changeTone: "green",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "已构建",
    buildTone: "green",
    lastInventoryAt: "2026-05-27 08:15",
    lastBuiltAt: "2026-05-27 08:54",
    chunks: 68,
    vectors: 68,
  },
  {
    id: "db-asset-ticket-sla",
    sourceId: "source-009",
    name: "vw_ticket_sla_summary",
    displayName: "工单 SLA 汇总",
    type: "视图",
    database: "service_prod",
    schema: "mart",
    comment: "客服 SLA 汇总视图，按业务线统计响应时长、解决时长和超时率。",
    fieldCount: 21,
    primaryKey: "",
    relationCount: 4,
    rowCount: "按查询生成",
    size: "视图",
    changeStatus: "字段变更",
    changeTone: "blue",
    buildability: "可构建",
    buildabilityTone: "green",
    buildStatus: "待重建",
    buildTone: "blue",
    lastInventoryAt: "2026-05-27 08:13",
    lastBuiltAt: "2026-05-26 19:22",
    chunks: 36,
    vectors: 36,
  },
];

window.MockData.databaseRelations = [
  {
    id: "rel-opportunity-customer",
    sourceId: "source-004",
    type: "外键",
    from: "db-asset-crm-opportunity",
    fromField: "customer_id",
    to: "db-asset-crm-customer",
    toField: "customer_id",
    evidence: "information_schema.table_constraints",
  },
  {
    id: "rel-contact-customer",
    sourceId: "source-004",
    type: "外键",
    from: "db-asset-crm-contact",
    fromField: "customer_id",
    to: "db-asset-crm-customer",
    toField: "customer_id",
    evidence: "information_schema.table_constraints",
  },
  {
    id: "rel-contract-customer",
    sourceId: "source-004",
    type: "外键",
    from: "db-asset-contract",
    fromField: "customer_id",
    to: "db-asset-crm-customer",
    toField: "customer_id",
    evidence: "information_schema.table_constraints",
  },
  {
    id: "rel-customer-tag-customer",
    sourceId: "source-004",
    type: "外键",
    from: "db-asset-customer-tag",
    fromField: "customer_id",
    to: "db-asset-crm-customer",
    toField: "customer_id",
    evidence: "information_schema.table_constraints",
  },
  {
    id: "rel-opportunity-product",
    sourceId: "source-004",
    type: "推断关系",
    from: "db-asset-crm-opportunity",
    fromField: "product_id",
    to: "db-asset-product",
    toField: "product_id",
    evidence: "字段命名 + 注释相似度",
  },
  {
    id: "rel-customer-region",
    sourceId: "source-004",
    type: "推断关系",
    from: "db-asset-crm-customer",
    fromField: "region_id",
    to: "db-asset-region",
    toField: "region_id",
    evidence: "字段命名 + 枚举分布",
  },
  {
    id: "rel-sales-order-opportunity",
    sourceId: "source-004",
    type: "视图依赖",
    from: "db-asset-sales-order-view",
    fromField: "opportunity_id",
    to: "db-asset-crm-opportunity",
    toField: "opportunity_id",
    evidence: "pg_depend / view definition",
  },
  {
    id: "rel-sales-order-contract",
    sourceId: "source-004",
    type: "视图依赖",
    from: "db-asset-sales-order-view",
    fromField: "contract_id",
    to: "db-asset-contract",
    toField: "contract_id",
    evidence: "pg_depend / view definition",
  },
  {
    id: "rel-funnel-opportunity",
    sourceId: "source-004",
    type: "物化视图依赖",
    from: "db-asset-sales-funnel-view",
    fromField: "opportunity_id",
    to: "db-asset-crm-opportunity",
    toField: "opportunity_id",
    evidence: "materialized view definition",
  },
  {
    id: "rel-activity-customer",
    sourceId: "source-004",
    type: "推断关系",
    from: "db-asset-activity",
    fromField: "customer_id",
    to: "db-asset-crm-customer",
    toField: "customer_id",
    evidence: "字段命名 + 业务注释",
  },
  {
    id: "rel-ticket-sla-ticket",
    sourceId: "source-009",
    type: "视图依赖",
    from: "db-asset-ticket-sla",
    fromField: "ticket_id",
    to: "db-asset-ticket-case",
    toField: "ticket_id",
    evidence: "view definition",
  },
];

window.MockData.assetDetails = {
  "asset-001": {
    assetId: "asset-001",
    sourceType: "文件系统",
    connectorType: "本地上传",
    minioObjectPath: "minio://dslm-data/raw/source-local-upload-sales/2026/05/27/products/product-intro.pdf",
    parsedMarkdownPath: "minio://dslm-data/parsed/source-local-upload-sales/asset-001/knowledge/latest/document.md",
    contentListPath: "minio://dslm-data/parsed/source-local-upload-sales/asset-001/knowledge/latest/content_list.json",
    contentStructure: [
      { type: "text", label: "正文", count: 18 },
      { type: "title", label: "标题", count: 9 },
      { type: "table", label: "表格", count: 3 },
      { type: "image", label: "图片", count: 2 },
      { type: "formula", label: "公式", count: 0 },
      { type: "list", label: "列表", count: 5 },
    ],
    vectorSummaries: [
      { sliceType: "正文", collection: "sales_docs_body_vectors", model: "bge-m3-enterprise", dimension: 1024 },
      { sliceType: "摘要", collection: "sales_docs_summary_vectors", model: "bge-m3-enterprise", dimension: 1024 },
    ],
    vectors: [
      { id: "vec-001-001", sliceType: "正文", collection: "sales_docs_body_vectors", model: "bge-m3-enterprise", dimension: 1024, chunkId: "chunk-001-001", page: 1, preview: "dslm-data 是面向企业数据资产的加工平台，支持资产盘点和知识构建。" },
      { id: "vec-001-002", sliceType: "正文", collection: "sales_docs_body_vectors", model: "bge-m3-enterprise", dimension: 1024, chunkId: "chunk-001-002", page: 2, preview: "产品资料会保留来源定位、标题路径和资产指纹，便于后续追踪。" },
      { id: "vec-001-003", sliceType: "正文", collection: "sales_docs_body_vectors", model: "bge-m3-enterprise", dimension: 1024, chunkId: "chunk-001-003", page: 3, preview: "平台负责解析、切片、embedding 生成和向量写入，不负责检索问答。" },
      { id: "vec-001-004", sliceType: "摘要", collection: "sales_docs_summary_vectors", model: "bge-m3-enterprise", dimension: 1024, chunkId: "summary-001-001", page: 0, preview: "产品介绍围绕数据源接入、资产盘点、知识构建和变更维护展开。" },
      { id: "vec-001-005", sliceType: "正文", collection: "sales_docs_body_vectors", model: "bge-m3-enterprise", dimension: 1024, chunkId: "chunk-001-004", page: 4, preview: "本地上传文件以 MinIO 对象路径作为源端引用。" },
      { id: "vec-001-006", sliceType: "摘要", collection: "sales_docs_summary_vectors", model: "bge-m3-enterprise", dimension: 1024, chunkId: "summary-001-002", page: 0, preview: "构建结果包含 markdown、content_list、chunk 和向量映射。" },
    ],
    chunks: [
      { id: "chunk-001-001", sliceType: "正文", titlePath: "产品概述 / 平台定位", page: 1, tokens: 486, status: "已向量化", preview: "dslm-data 是面向企业数据资产的加工平台，支持资产盘点和知识构建。" },
      { id: "chunk-001-002", sliceType: "正文", titlePath: "核心能力 / 资产盘点", page: 2, tokens: 392, status: "已向量化", preview: "资产盘点只登记元数据和来源引用，不搬运源端原始数据。" },
      { id: "chunk-001-003", sliceType: "正文", titlePath: "核心能力 / 知识构建", page: 3, tokens: 528, status: "已向量化", preview: "知识构建会解析文件，生成 markdown、content_list、chunk 和 embedding。" },
      { id: "chunk-001-004", sliceType: "正文", titlePath: "接入方式 / 本地上传", page: 4, tokens: 244, status: "已向量化", preview: "本地上传文件在 MinIO 中保存完整对象路径，构建任务按资产引用读取。" },
      { id: "summary-001-001", sliceType: "摘要", titlePath: "文档摘要", page: 0, tokens: 180, status: "已向量化", preview: "产品介绍围绕数据源接入、资产盘点、知识构建和变更维护展开。" },
      { id: "summary-001-002", sliceType: "摘要", titlePath: "构建摘要", page: 0, tokens: 156, status: "已向量化", preview: "构建结果包含 markdown、切片和向量映射，供后续检索系统使用。" },
    ],
  },
};

window.MockData.uploadRows = [
  { name: "产品介绍.pdf", relativePath: "产品资料/产品介绍.pdf", type: "PDF", size: "8.4 MB", stage: "登记完成", status: "上传成功", tone: "green", progress: 100, note: "已登记资产元数据" },
  { name: "销售话术.docx", relativePath: "销售资料/话术/销售话术.docx", type: "Word", size: "1.7 MB", stage: "登记资产中", status: "登记资产中", tone: "blue", progress: 92, note: "正在写入资产身份和 MinIO 引用", canCancel: true },
  { name: "报价模板.xlsx", relativePath: "销售资料/模板/报价模板.xlsx", type: "Excel", size: "640 KB", stage: "上传中断", status: "上传失败", tone: "red", progress: 64, note: "网络中断，可从断点继续或重传", canRetry: true },
  { name: "销售话术.docx", relativePath: "销售资料/话术/销售话术.docx", type: "Word", size: "1.8 MB", stage: "上传中", status: "上传中", tone: "blue", progress: 48, note: "同路径资产，上传后比较 hash，变化则登记为更新", canCancel: true },
  { name: "空白说明.txt", relativePath: "销售资料/空白说明.txt", type: "TXT", size: "0 KB", stage: "上传前校验", status: "已拦截", tone: "red", progress: 0, note: "空文件不可选择", blocked: true },
  { name: "合同扫描.zip", relativePath: "合同扫描/合同扫描.zip", type: "ZIP", size: "41.2 MB", stage: "上传前校验", status: "已拦截", tone: "red", progress: 0, note: "压缩包不可选择", blocked: true },
];

window.MockData.buildTaskPreviewAssets = {
  知识: [
    { id: "asset-001", name: "产品介绍.pdf", type: "PDF", size: "8.4 MB", state: "已是最新", tone: "green", fingerprint: "8af2...91c0", reason: "同解析策略下已成功构建，资产指纹未变化", canBuild: false },
    { id: "asset-002", name: "销售话术.docx", type: "Word", size: "1.7 MB", state: "未构建", tone: "amber", fingerprint: "6e19...f3a2", reason: "知识解析下没有成功构建记录", canBuild: true },
    { id: "asset-003", name: "报价模板.xlsx", type: "Excel", size: "640 KB", state: "构建失败", tone: "red", fingerprint: "44de...7b90", reason: "上次构建失败，允许重试", canBuild: true },
    { id: "asset-004", name: "客户案例合集.pptx", type: "PPT", size: "22.1 MB", state: "已是最新", tone: "green", fingerprint: "c8a0...2db1", reason: "同解析策略下已成功构建，资产指纹未变化", canBuild: false },
    { id: "asset-005", name: "扫描合同.png", type: "Image", size: "3.8 MB", state: "已变更", tone: "blue", fingerprint: "2359...b5d4", reason: "资产指纹与上次构建记录不一致", canBuild: true },
    { id: "asset-006", name: "加密协议.pdf", type: "PDF", size: "2.6 MB", state: "不可构建", tone: "red", fingerprint: "1f70...dad2", reason: "加密文件，无法解析", canBuild: false },
  ],
  规则: [
    { id: "asset-001", name: "产品介绍.pdf", type: "PDF", size: "8.4 MB", state: "未构建", tone: "amber", fingerprint: "8af2...91c0", reason: "规则解析下没有成功构建记录", canBuild: true },
    { id: "asset-002", name: "销售话术.docx", type: "Word", size: "1.7 MB", state: "未构建", tone: "amber", fingerprint: "6e19...f3a2", reason: "规则解析下没有成功构建记录", canBuild: true },
    { id: "asset-003", name: "报价模板.xlsx", type: "Excel", size: "640 KB", state: "未构建", tone: "amber", fingerprint: "44de...7b90", reason: "规则解析下没有成功构建记录", canBuild: true },
    { id: "asset-004", name: "客户案例合集.pptx", type: "PPT", size: "22.1 MB", state: "未构建", tone: "amber", fingerprint: "c8a0...2db1", reason: "规则解析下没有成功构建记录", canBuild: true },
    { id: "asset-005", name: "扫描合同.png", type: "Image", size: "3.8 MB", state: "未构建", tone: "amber", fingerprint: "2359...b5d4", reason: "规则解析下没有成功构建记录", canBuild: true },
    { id: "asset-006", name: "加密协议.pdf", type: "PDF", size: "2.6 MB", state: "不可构建", tone: "red", fingerprint: "1f70...dad2", reason: "加密文件，无法解析", canBuild: false },
  ],
  问答: [
    { id: "asset-001", name: "产品介绍.pdf", type: "PDF", size: "8.4 MB", state: "未构建", tone: "amber", fingerprint: "8af2...91c0", reason: "问答解析下没有成功构建记录", canBuild: true },
    { id: "asset-002", name: "销售话术.docx", type: "Word", size: "1.7 MB", state: "未构建", tone: "amber", fingerprint: "6e19...f3a2", reason: "问答解析下没有成功构建记录", canBuild: true },
    { id: "asset-003", name: "报价模板.xlsx", type: "Excel", size: "640 KB", state: "未构建", tone: "amber", fingerprint: "44de...7b90", reason: "问答解析下没有成功构建记录", canBuild: true },
    { id: "asset-004", name: "客户案例合集.pptx", type: "PPT", size: "22.1 MB", state: "未构建", tone: "amber", fingerprint: "c8a0...2db1", reason: "问答解析下没有成功构建记录", canBuild: true },
    { id: "asset-005", name: "扫描合同.png", type: "Image", size: "3.8 MB", state: "未构建", tone: "amber", fingerprint: "2359...b5d4", reason: "问答解析下没有成功构建记录", canBuild: true },
    { id: "asset-006", name: "加密协议.pdf", type: "PDF", size: "2.6 MB", state: "不可构建", tone: "red", fingerprint: "1f70...dad2", reason: "加密文件，无法解析", canBuild: false },
  ],
};

window.MockData.buildTaskPreviewResponses = {
  知识: {
    previewId: "preview-local-knowledge-001",
    summary: "后端返回：当前任务采用知识解析，共 5 个关键执行步骤。",
    steps: [
      { order: 1, title: "校验资产", description: "校验资产状态、文件引用和内容指纹。", outputs: ["可构建资产", "跳过原因"] },
      { order: 2, title: "知识解析", description: "抽取正文、标题层级、表格和来源定位。", outputs: ["markdown", "结构化内容"] },
      { order: 3, title: "切片", description: "按系统配置生成 chunk，并保留资产位置。", outputs: ["chunk 文本", "metadata"] },
      { order: 4, title: "生成向量", description: "调用系统 embedding 服务生成向量。", outputs: ["embedding", "模型版本"] },
      { order: 5, title: "写入结果", description: "写入向量库并登记构建产物。", outputs: ["vector id", "任务报告"] },
    ],
  },
  规则: {
    previewId: "preview-local-rule-001",
    summary: "后端返回：当前任务采用规则解析，共 5 个关键执行步骤。",
    steps: [
      { order: 1, title: "校验资产", description: "校验资产状态、文件引用和内容指纹。", outputs: ["可构建资产", "跳过原因"] },
      { order: 2, title: "规则解析", description: "按模板和字段规则抽取结构化内容。", outputs: ["字段值", "校验结果"] },
      { order: 3, title: "切片", description: "按系统配置生成 chunk，并保留规则来源。", outputs: ["chunk 文本", "规则 metadata"] },
      { order: 4, title: "生成向量", description: "调用系统 embedding 服务生成向量。", outputs: ["embedding", "模型版本"] },
      { order: 5, title: "写入结果", description: "写入向量库并登记构建产物。", outputs: ["vector id", "任务报告"] },
    ],
  },
  问答: {
    previewId: "preview-local-qa-001",
    summary: "后端返回：当前任务采用问答解析，共 5 个关键执行步骤。",
    steps: [
      { order: 1, title: "校验资产", description: "校验资产状态、文件引用和内容指纹。", outputs: ["可构建资产", "跳过原因"] },
      { order: 2, title: "问答解析", description: "抽取问题、答案证据和可追溯来源。", outputs: ["问题线索", "答案证据"] },
      { order: 3, title: "切片", description: "按系统配置生成 chunk，并保留问答上下文。", outputs: ["chunk 文本", "问答 metadata"] },
      { order: 4, title: "生成向量", description: "调用系统 embedding 服务生成向量。", outputs: ["embedding", "模型版本"] },
      { order: 5, title: "写入结果", description: "写入向量库并登记构建产物。", outputs: ["vector id", "任务报告"] },
    ],
  },
};

window.MockData.buildTaskCreateResponse = {
  statusLabel: "构建任务已创建",
  statusTone: "green",
  message: "后端已根据 previewId 创建任务，并固化执行链路、资产范围、解析策略和自动维护规则。",
  redirectUrl: "local-upload-detail.html?createdTask=1#tasks",
};

window.MockData.createdBuildTask = {
  id: "build-new",
  name: "销售资料构建任务",
  scope: "部分资产",
  scopeTone: "blue",
  source: "手动创建",
  createdAt: "刚刚",
  status: "排队中",
  tone: "amber",
  assets: 3,
  chunks: 0,
  vectors: 0,
  href: "task-detail.html?id=build-new",
};

window.MockData.buildTasks = [
  { id: "build-001", name: "销售资料首批构建", scope: "全部资产", scopeTone: "green", source: "手动创建", createdAt: "2026-05-27 14:42", status: "成功", tone: "green", assets: 8, chunks: 198, vectors: 198, href: "task-detail.html?id=build-001" },
  { id: "build-002", name: "新增文件自动构建", scope: "全部资产", scopeTone: "green", source: "变更自动", createdAt: "2026-05-27 15:20", status: "运行中", tone: "blue", assets: 7, chunks: 48, vectors: 32, href: "task-detail.html?id=build-002" },
  { id: "build-003", name: "产品介绍更新重建", scope: "全部资产", scopeTone: "green", source: "变更自动", createdAt: "2026-05-27 15:22", status: "排队中", tone: "amber", assets: 1, chunks: 0, vectors: 0, href: "task-detail.html?id=build-003" },
  { id: "build-004", name: "报价模板重试", scope: "部分资产", scopeTone: "blue", source: "失败重试", createdAt: "2026-05-27 15:03", status: "失败", tone: "red", assets: 1, chunks: 0, vectors: 0, href: "task-detail.html?id=build-004" },
  { id: "build-005", name: "客户分层构建任务", scope: "部分资产", scopeTone: "blue", source: "手动创建", createdAt: "2026-05-27 15:08", status: "已停止", tone: "amber", assets: 4, chunks: 24, vectors: 16, href: "task-detail.html?id=build-005" },
  { id: "build-006", name: "销售问答规则构建", scope: "部分资产", scopeTone: "blue", source: "手动创建", createdAt: "2026-05-27 15:26", status: "待启动", tone: "blue", assets: 2, chunks: 0, vectors: 0, href: "task-detail.html?id=build-006" },
];

window.MockData.buildTaskDetails = {
  "build-new": {
    parseStrategy: "知识",
    metrics: { totalAssets: 3, completedAssets: 0, runningAssets: 0, failedAssets: 0, chunks: 0, vectors: 0 },
    stages: [
      { order: 1, title: "校验资产", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 3, failed: 0 },
      { order: 2, title: "知识解析", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 3, failed: 0 },
      { order: 3, title: "切片", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 3, failed: 0 },
      { order: 4, title: "生成向量", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 3, failed: 0 },
      { order: 5, title: "写入结果", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 3, failed: 0 },
    ],
    assets: [
      { assetId: "asset-002", name: "销售话术.docx", type: "Word", status: "排队中", tone: "amber", stage: "校验资产", progress: 0, chunks: 0, vectors: 0, duration: "-", updatedAt: "刚刚" },
      { assetId: "asset-003", name: "报价模板.xlsx", type: "Excel", status: "排队中", tone: "amber", stage: "校验资产", progress: 0, chunks: 0, vectors: 0, duration: "-", updatedAt: "刚刚" },
      { assetId: "asset-005", name: "扫描合同.png", type: "Image", status: "排队中", tone: "amber", stage: "校验资产", progress: 0, chunks: 0, vectors: 0, duration: "-", updatedAt: "刚刚" },
    ],
  },
  "build-001": {
    parseStrategy: "知识",
    metrics: { totalAssets: 8, completedAssets: 8, runningAssets: 0, failedAssets: 0, chunks: 198, vectors: 198 },
    stages: [
      { order: 1, title: "校验资产", status: "已完成", statusClass: "done", done: 8, running: 0, pending: 0, failed: 0 },
      { order: 2, title: "知识解析", status: "已完成", statusClass: "done", done: 8, running: 0, pending: 0, failed: 0 },
      { order: 3, title: "切片", status: "已完成", statusClass: "done", done: 8, running: 0, pending: 0, failed: 0 },
      { order: 4, title: "生成向量", status: "已完成", statusClass: "done", done: 8, running: 0, pending: 0, failed: 0 },
      { order: 5, title: "写入结果", status: "已完成", statusClass: "done", done: 8, running: 0, pending: 0, failed: 0 },
    ],
    assets: [
      { assetId: "asset-001", name: "产品介绍.pdf", type: "PDF", status: "成功", tone: "green", stage: "写入结果", progress: 100, chunks: 32, vectors: 32, duration: "46 秒", updatedAt: "2026-05-27 14:48" },
      { assetId: "asset-002", name: "销售话术.docx", type: "Word", status: "成功", tone: "green", stage: "写入结果", progress: 100, chunks: 18, vectors: 18, duration: "31 秒", updatedAt: "2026-05-27 14:49" },
      { assetId: "asset-003", name: "报价模板.xlsx", type: "Excel", status: "成功", tone: "green", stage: "写入结果", progress: 100, chunks: 12, vectors: 12, duration: "29 秒", updatedAt: "2026-05-27 14:49" },
      { assetId: "asset-004", name: "客户案例合集.pptx", type: "PPT", status: "成功", tone: "green", stage: "写入结果", progress: 100, chunks: 74, vectors: 74, duration: "1 分 18 秒", updatedAt: "2026-05-27 14:51" },
      { assetId: "asset-007", name: "培训材料.md", type: "Markdown", status: "成功", tone: "green", stage: "写入结果", progress: 100, chunks: 16, vectors: 16, duration: "24 秒", updatedAt: "2026-05-27 14:52" },
      { assetId: "asset-008", name: "客户清单.csv", type: "CSV", status: "成功", tone: "green", stage: "写入结果", progress: 100, chunks: 10, vectors: 10, duration: "21 秒", updatedAt: "2026-05-27 14:52" },
      { assetId: "asset-009", name: "续费流程.pdf", type: "PDF", status: "成功", tone: "green", stage: "写入结果", progress: 100, chunks: 24, vectors: 24, duration: "39 秒", updatedAt: "2026-05-27 14:53" },
      { assetId: "asset-010", name: "售前问答.xlsx", type: "Excel", status: "成功", tone: "green", stage: "写入结果", progress: 100, chunks: 12, vectors: 12, duration: "33 秒", updatedAt: "2026-05-27 14:53" },
    ],
  },
  "build-002": {
    parseStrategy: "知识",
    metrics: { totalAssets: 7, completedAssets: 2, runningAssets: 2, failedAssets: 0, chunks: 48, vectors: 32 },
    stages: [
      { order: 1, title: "校验资产", status: "已完成", statusClass: "done", done: 7, running: 0, pending: 0, failed: 0 },
      { order: 2, title: "知识解析", status: "运行中", statusClass: "running", done: 4, running: 2, pending: 1, failed: 0 },
      { order: 3, title: "切片", status: "运行中", statusClass: "running", done: 3, running: 1, pending: 3, failed: 0 },
      { order: 4, title: "生成向量", status: "运行中", statusClass: "running", done: 2, running: 1, pending: 4, failed: 0 },
      { order: 5, title: "写入结果", status: "运行中", statusClass: "running", done: 2, running: 0, pending: 5, failed: 0 },
    ],
    assets: [
      { assetId: "asset-011", name: "销售政策.txt", type: "TXT", status: "成功", tone: "green", stage: "写入结果", progress: 100, chunks: 14, vectors: 14, duration: "26 秒", updatedAt: "2026-05-27 15:22" },
      { assetId: "asset-012", name: "客户回访记录.docx", type: "Word", status: "成功", tone: "green", stage: "写入结果", progress: 100, chunks: 18, vectors: 18, duration: "34 秒", updatedAt: "2026-05-27 15:23" },
      { assetId: "asset-005", name: "扫描合同.png", type: "Image", status: "运行中", tone: "blue", stage: "生成向量", progress: 72, chunks: 16, vectors: 0, duration: "42 秒", updatedAt: "2026-05-27 15:24" },
      { assetId: "asset-003", name: "报价模板.xlsx", type: "Excel", status: "运行中", tone: "blue", stage: "切片", progress: 58, chunks: 0, vectors: 0, duration: "37 秒", updatedAt: "2026-05-27 15:24" },
      { assetId: "asset-009", name: "续费流程.pdf", type: "PDF", status: "等待中", tone: "amber", stage: "知识解析", progress: 28, chunks: 0, vectors: 0, duration: "-", updatedAt: "2026-05-27 15:24" },
      { assetId: "asset-010", name: "售前问答.xlsx", type: "Excel", status: "等待中", tone: "amber", stage: "知识解析", progress: 20, chunks: 0, vectors: 0, duration: "-", updatedAt: "2026-05-27 15:24" },
      { assetId: "asset-007", name: "培训材料.md", type: "Markdown", status: "未开始", tone: "amber", stage: "校验资产", progress: 0, chunks: 0, vectors: 0, duration: "-", updatedAt: "2026-05-27 15:24" },
    ],
  },
  "build-003": {
    parseStrategy: "知识",
    metrics: { totalAssets: 1, completedAssets: 0, runningAssets: 0, failedAssets: 0, chunks: 0, vectors: 0 },
    stages: [
      { order: 1, title: "校验资产", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 1, failed: 0 },
      { order: 2, title: "知识解析", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 1, failed: 0 },
      { order: 3, title: "切片", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 1, failed: 0 },
      { order: 4, title: "生成向量", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 1, failed: 0 },
      { order: 5, title: "写入结果", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 1, failed: 0 },
    ],
    assets: [
      { assetId: "asset-001", name: "产品介绍.pdf", type: "PDF", status: "排队中", tone: "amber", stage: "校验资产", progress: 0, chunks: 0, vectors: 0, duration: "-", updatedAt: "2026-05-27 15:22" },
    ],
  },
  "build-004": {
    parseStrategy: "知识",
    metrics: { totalAssets: 1, completedAssets: 0, runningAssets: 0, failedAssets: 1, chunks: 0, vectors: 0 },
    stages: [
      { order: 1, title: "校验资产", status: "已完成", statusClass: "done", done: 1, running: 0, pending: 0, failed: 0 },
      { order: 2, title: "知识解析", status: "失败", statusClass: "failed", done: 0, running: 0, pending: 0, failed: 1 },
      { order: 3, title: "切片", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 1, failed: 0 },
      { order: 4, title: "生成向量", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 1, failed: 0 },
      { order: 5, title: "写入结果", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 1, failed: 0 },
    ],
    assets: [
      { assetId: "asset-003", name: "报价模板.xlsx", type: "Excel", status: "失败", tone: "red", stage: "知识解析", progress: 36, chunks: 0, vectors: 0, duration: "18 秒", updatedAt: "2026-05-27 15:04" },
    ],
  },
  "build-005": {
    parseStrategy: "知识",
    metrics: { totalAssets: 4, completedAssets: 1, runningAssets: 0, failedAssets: 0, chunks: 24, vectors: 16 },
    stages: [
      { order: 1, title: "校验资产", status: "已完成", statusClass: "done", done: 4, running: 0, pending: 0, failed: 0 },
      { order: 2, title: "知识解析", status: "已停止", statusClass: "pending", done: 2, running: 0, pending: 2, failed: 0 },
      { order: 3, title: "切片", status: "已停止", statusClass: "pending", done: 1, running: 0, pending: 3, failed: 0 },
      { order: 4, title: "生成向量", status: "已停止", statusClass: "pending", done: 1, running: 0, pending: 3, failed: 0 },
      { order: 5, title: "写入结果", status: "已停止", statusClass: "pending", done: 1, running: 0, pending: 3, failed: 0 },
    ],
    assets: [
      { assetId: "asset-012", name: "客户分层策略.pptx", type: "PPT", status: "成功", tone: "green", stage: "写入结果", progress: 100, chunks: 24, vectors: 16, duration: "52 秒", updatedAt: "2026-05-27 15:09" },
      { assetId: "asset-011", name: "区域报价说明.docx", type: "Word", status: "已停止", tone: "amber", stage: "知识解析", progress: 42, chunks: 0, vectors: 0, duration: "-", updatedAt: "2026-05-27 15:10" },
      { assetId: "asset-010", name: "售前问答.xlsx", type: "Excel", status: "未开始", tone: "amber", stage: "校验资产", progress: 0, chunks: 0, vectors: 0, duration: "-", updatedAt: "2026-05-27 15:10" },
      { assetId: "asset-007", name: "渠道政策.md", type: "Markdown", status: "未开始", tone: "amber", stage: "校验资产", progress: 0, chunks: 0, vectors: 0, duration: "-", updatedAt: "2026-05-27 15:10" },
    ],
  },
  "build-006": {
    parseStrategy: "问答",
    metrics: { totalAssets: 2, completedAssets: 0, runningAssets: 0, failedAssets: 0, chunks: 0, vectors: 0 },
    stages: [
      { order: 1, title: "校验资产", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 2, failed: 0 },
      { order: 2, title: "问答解析", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 2, failed: 0 },
      { order: 3, title: "切片", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 2, failed: 0 },
      { order: 4, title: "生成向量", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 2, failed: 0 },
      { order: 5, title: "写入结果", status: "未开始", statusClass: "pending", done: 0, running: 0, pending: 2, failed: 0 },
    ],
    assets: [
      { assetId: "asset-007", name: "渠道政策.md", type: "Markdown", status: "未开始", tone: "amber", stage: "校验资产", progress: 0, chunks: 0, vectors: 0, duration: "-", updatedAt: "2026-05-27 15:26" },
      { assetId: "asset-008", name: "竞品对比.txt", type: "TXT", status: "未开始", tone: "amber", stage: "校验资产", progress: 0, chunks: 0, vectors: 0, duration: "-", updatedAt: "2026-05-27 15:26" },
    ],
  },
};

window.MockData.artifactSummary = {
  parsed: 4,
  chunks: 126,
  vectors: 126,
};

const artifactAssetRefs = [
  { assetId: "asset-001", name: "产品介绍.pdf", type: "PDF", slug: "product-intro" },
  { assetId: "asset-002", name: "销售话术.docx", type: "Word", slug: "sales-script" },
  { assetId: "asset-003", name: "报价模板.xlsx", type: "Excel", slug: "quotation-template" },
  { assetId: "asset-004", name: "客户案例合集.pptx", type: "PPT", slug: "customer-cases" },
];

const parsedArtifacts = artifactAssetRefs.map((asset, index) => ({
  id: `parsed-${String(index + 1).padStart(3, "0")}`,
  type: "解析产物",
  name: `${asset.name} / document.md`,
  assetName: asset.name,
  subtype: "Markdown",
  location: `minio://dslm-data/parsed/source-local-upload-sales/${asset.assetId}/knowledge/latest/document.md`,
  status: "可预览",
  statusTone: "green",
  updatedAt: `2026-05-27 14:${48 + index}`,
  preview: `# ${asset.name}\n\n## 解析结果\n- 解析策略：知识\n- 资产类型：${asset.type}\n- 输出格式：Markdown\n- 关联 content_list：minio://dslm-data/parsed/source-local-upload-sales/${asset.assetId}/knowledge/latest/content_list.json\n\n这里展示后端解析后的 Markdown 摘要，完整内容保存在 MinIO。`,
}));

const chunkArtifacts = Array.from({ length: 126 }, (_, index) => {
  const asset = artifactAssetRefs[index % artifactAssetRefs.length];
  const number = index + 1;
  const sliceType = index % 9 === 0 ? "摘要" : "正文";
  const chunkId = `chunk-${String(number).padStart(4, "0")}`;
  return {
    id: chunkId,
    type: "切片",
    name: chunkId,
    assetName: asset.name,
    subtype: sliceType,
    location: `dslm://chunks/source-local-upload-sales/${asset.assetId}/${chunkId}`,
    status: "已生成",
    statusTone: "green",
    updatedAt: `2026-05-27 14:${String(50 + (index % 8)).padStart(2, "0")}`,
    preview: `Chunk ID: ${chunkId}\n关联资产: ${asset.name}\n切片类型: ${sliceType}\nToken 数: ${260 + (index % 11) * 18}\n\n这是 ${asset.name} 的${sliceType}切片内容预览。切片保留标题路径、页码、源文件位置和构建任务信息，供后续向量写入与检索系统使用。`,
  };
});

const vectorArtifacts = Array.from({ length: 126 }, (_, index) => {
  const asset = artifactAssetRefs[index % artifactAssetRefs.length];
  const number = index + 1;
  const sliceType = index % 9 === 0 ? "摘要" : "正文";
  const chunkId = `chunk-${String(number).padStart(4, "0")}`;
  const vectorId = `vec-${String(number).padStart(4, "0")}`;
  const collection = sliceType === "摘要" ? "sales_docs_summary_vectors" : "sales_docs_body_vectors";
  return {
    id: vectorId,
    type: "向量",
    name: vectorId,
    assetName: asset.name,
    subtype: sliceType,
    location: collection,
    status: "已写入",
    statusTone: "green",
    updatedAt: `2026-05-27 14:${String(52 + (index % 7)).padStart(2, "0")}`,
    preview: `Vector ID: ${vectorId}\nCollection: ${collection}\n模型: bge-m3-enterprise\n维度: 1024\n关联 Chunk: ${chunkId}\n关联资产: ${asset.name}\n\n向量预览: [0.${(17 + index) % 100}, -0.${(23 + index) % 100}, 0.${(41 + index) % 100}, ...]\n\n这里只展示向量元数据和截断后的向量片段，完整向量由后端写入向量库。`,
  };
});

window.MockData.buildArtifacts = [...parsedArtifacts, ...chunkArtifacts, ...vectorArtifacts];

window.MockData.changeEvents = [
  {
    id: "change-new-files",
    type: "新增文件",
    count: 3,
    relatedTask: "新增文件自动构建",
    relatedTaskHref: "task-detail.html?id=build-002",
    action: "创建构建任务",
    status: "运行中",
    statusTone: "blue",
    details: [
      { name: "销售政策.txt", type: "TXT", change: "新增文档", sourcePath: "minio://dslm-data/raw/source-local-upload-sales/2026/05/27/policy/sales-policy.txt", beforeFingerprint: "", afterFingerprint: "sha256: a1c8...72df", detectedAt: "2026-05-27 15:18" },
      { name: "客户回访记录.docx", type: "Word", change: "新增文档", sourcePath: "minio://dslm-data/raw/source-local-upload-sales/2026/05/27/visit/customer-visit.docx", beforeFingerprint: "", afterFingerprint: "sha256: b72a...5e19", detectedAt: "2026-05-27 15:18" },
      { name: "培训材料.md", type: "Markdown", change: "新增文档", sourcePath: "minio://dslm-data/raw/source-local-upload-sales/2026/05/27/training/playbook.md", beforeFingerprint: "", afterFingerprint: "sha256: c03f...88ab", detectedAt: "2026-05-27 15:19" },
    ],
  },
  {
    id: "change-updated-files",
    type: "文件内容更新",
    count: 1,
    relatedTask: "产品介绍更新重建",
    relatedTaskHref: "task-detail.html?id=build-003",
    action: "创建重建任务",
    status: "已创建任务",
    statusTone: "amber",
    details: [
      { name: "产品介绍.pdf", type: "PDF", change: "内容指纹变化", sourcePath: "minio://dslm-data/raw/source-local-upload-sales/2026/05/27/products/product-intro.pdf", beforeFingerprint: "sha256: 8af2...91c0", afterFingerprint: "sha256: 9b31...0c74", detectedAt: "2026-05-27 15:21" },
    ],
  },
  {
    id: "change-deleted-files",
    type: "文件删除",
    count: 1,
    relatedTask: "删除文件清理任务",
    relatedTaskHref: "",
    action: "创建清理任务",
    status: "等待执行",
    statusTone: "amber",
    details: [
      { name: "旧版报价说明.pdf", type: "PDF", change: "源端文件删除", sourcePath: "minio://dslm-data/raw/source-local-upload-sales/2026/05/20/archive/old-pricing.pdf", beforeFingerprint: "sha256: 77d1...ab09", afterFingerprint: "", detectedAt: "2026-05-27 15:22" },
    ],
  },
];

window.MockData.auditEvents = [
  { time: "2026-05-27 15:12", actor: "系统", action: "写入向量库", detail: "客户案例合集.pptx 写入 74 条向量记录" },
  { time: "2026-05-27 14:42", actor: "王敏", action: "创建构建任务", detail: "范围：全部资产" },
  { time: "2026-05-27 14:20", actor: "王敏", action: "创建数据源", detail: "销售资料上传区" },
];
